import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, Clock, Calendar, ArrowRight } from 'lucide-react';
import { fetchBlogPostServer, fetchBlogPostsServer } from '@/hooks/useBlog';
import { ArticleSchema } from '@/components/seo/ArticleSchema';
import { ArticleContent } from '@/components/help/ArticleContent';
import { BlogCard } from '@/components/blog/BlogCard';
import { BlogFaq } from '@/components/blog/BlogFaq';

export const revalidate = 300; // 5 min ISR so edits show up quickly.

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ||
  `https://${process.env.NEXT_PUBLIC_MAIN_DOMAIN || 'echodesk.ge'}`;

const POST_TYPE_LABELS: Record<string, string> = {
  comparison: 'Comparison',
  how_to: 'How-To',
  use_case: 'Use Case',
  announcement: 'Announcement',
  thought_leadership: 'Perspective',
};

// Blog posts always render in Georgian for the default route. We
// deliberately do NOT call `cookies()` here — even though that would
// match the language-switcher cookie, it forces dynamic rendering
// which pushes generateMetadata out of the <head> chunk and into the
// streamed body, breaking link-unfurler previews (Slack, iMessage,
// FB Messenger, Telegram, WhatsApp). Going static + ka-default keeps
// per-article OG meta in <head> where scrapers can find it. English
// versions can be added later under /en/blog/<slug> as a separate
// statically-generated route.
const DEFAULT_LANG: 'ka' | 'en' = 'ka';

// -------------------------------------------------------------------
// Metadata
// -------------------------------------------------------------------

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = await fetchBlogPostServer(slug, DEFAULT_LANG).catch(() => null);
  if (!post) {
    return { title: 'Not found' };
  }

  const url = `${SITE_URL}/blog/${post.slug}`;
  return {
    title: post.meta_title || post.title,
    description: post.meta_description || post.summary,
    keywords: (post.keywords || []).join(', '),
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      siteName: 'EchoDesk',
      locale: DEFAULT_LANG === 'ka' ? 'ka_GE' : 'en_US',
      url,
      title: post.meta_title || post.title,
      description: post.meta_description || post.summary,
      publishedTime: post.published_at,
      modifiedTime: post.updated_at,
      // No `images:` override — let Next.js auto-inject the per-article
      // PNG generated by sibling opengraph-image.tsx so each post gets
      // its own card (title + tag + EchoDesk brand).
    },
    twitter: {
      card: 'summary_large_image',
      site: '@echodesk',
      creator: '@echodesk',
      title: post.meta_title || post.title,
      description: post.meta_description || post.summary,
      // Same — twitter:image picks up the same auto-generated PNG.
    },
  };
}

/**
 * Build-time static generation: list every published slug so Next.js
 * pre-renders each article into a static HTML file with metadata fully
 * resolved in <head>. Without this, the page is dynamic (because of the
 * fetch + revalidate) and Next.js streams metadata into the body — chat
 * unfurlers don't parse body, so per-article previews never render.
 *
 * dynamicParams = true (default) means new posts not in this list are
 * still rendered on demand and cached by ISR — the static prerender is
 * just a fast-path for known slugs at build time.
 */
export async function generateStaticParams() {
  try {
    const data = await fetchBlogPostsServer({
      lang: DEFAULT_LANG,
      pageSize: 500,
    });
    return (data.results || []).map((p) => ({ slug: p.slug }));
  } catch {
    // Build must not fail if the API is down — Next.js will fall back to
    // on-demand rendering for any slug.
    return [];
  }
}

// -------------------------------------------------------------------
// Page
// -------------------------------------------------------------------

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const lang = DEFAULT_LANG;
  const post = await fetchBlogPostServer(slug, lang).catch(() => null);
  if (!post) notFound();

  const url = `${SITE_URL}/blog/${post.slug}`;
  const label = POST_TYPE_LABELS[post.post_type] ?? post.post_type;
  const date = post.published_at
    ? new Date(post.published_at).toLocaleDateString(lang === 'ka' ? 'ka-GE' : 'en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : null;

  // Related posts: same category or same post_type, excluding this one.
  const relatedList = await fetchBlogPostsServer({
    lang,
    pageSize: 6,
    postType: post.post_type,
  }).catch(() => ({ count: 0, next: null, previous: null, results: [] }));
  const related = relatedList.results.filter((p) => p.slug !== post.slug).slice(0, 3);

  return (
    <>
      <ArticleSchema post={post} url={url} locale={lang} />
      <article className="container mx-auto max-w-3xl px-4 py-10 md:py-14">
        <Link
          href="/blog"
          className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          {lang === 'ka' ? 'ყველა პოსტი' : 'All posts'}
        </Link>

        <header className="mt-6 space-y-4">
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <span className="inline-flex items-center rounded-full bg-primary/10 text-primary px-2.5 py-0.5 font-semibold uppercase tracking-wider">
              {label}
            </span>
            {post.category?.name && (
              <Link
                href="/blog"
                className="text-muted-foreground hover:text-foreground"
              >
                {post.category.name}
              </Link>
            )}
          </div>

          <h1 className="text-3xl md:text-5xl font-bold tracking-tight leading-tight">
            {post.title}
          </h1>

          {post.summary && (
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
              {post.summary}
            </p>
          )}

          <div className="flex items-center gap-4 text-sm text-muted-foreground pt-2 border-t">
            {date && (
              <span className="inline-flex items-center gap-1.5">
                <Calendar className="h-4 w-4" />
                {date}
              </span>
            )}
            {post.reading_time_minutes > 0 && (
              <span className="inline-flex items-center gap-1.5">
                <Clock className="h-4 w-4" />
                {post.reading_time_minutes} {lang === 'ka' ? 'წთ' : 'min'}
              </span>
            )}
          </div>
        </header>

        {post.hero_image_url && (
          <div className="mt-8 rounded-2xl overflow-hidden bg-muted">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={post.hero_image_url}
              alt={post.title}
              className="w-full h-auto"
              loading="lazy"
              decoding="async"
            />
          </div>
        )}

        <div className="mt-10">
          <ArticleContent content={post.content_html} />
        </div>

        {/* In-content internal links — sit between the article body and
            the FAQ/CTA so search crawlers (and humans) see them when
            engagement is highest. Targets vary by post_type so a
            comparison post links to alternatives, a how-to to the docs,
            etc. — keeps internal authority flowing to the pages most
            relevant to each reader's intent. */}
        <aside className="mt-12 rounded-2xl border border-border bg-muted/30 p-6 md:p-8">
          <h2 className="text-base font-semibold mb-3 text-foreground">
            {lang === 'ka' ? 'სასარგებლო ბმულები' : 'You might also like'}
          </h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
            {(() => {
              type LinkItem = { href: string; label: string; hint: string };
              const all: Record<'ka' | 'en', LinkItem[]> = {
                ka: [
                  { href: '/pricing', label: 'ფასები ლარში', hint: 'გადაიხადე მხოლოდ რასაც იყენებ' },
                  { href: '/whatsapp-helpdesk-georgia', label: 'WhatsApp helpdesk', hint: 'მიიღე ყველა შეტყობინება ერთ ინბოქსში' },
                  { href: '/gel-invoicing-software', label: 'ლარში ინვოისები', hint: 'BOG-ისა და TBC-ის გადახდის ბმულებით' },
                  { href: '/sip-pbx-crm-georgia', label: 'SIP PBX + CRM', hint: 'ბრაუზერიდან ზარები ქართული ნომრით' },
                  { href: '/docs', label: 'დოკუმენტაცია', hint: 'PBX, ვიჯეტი, API setup' },
                  { href: '/contact', label: 'დემოს დაგეგმვა', hint: 'პირველი დღიდან მხარდაჭერა ქართულად' },
                ],
                en: [
                  { href: '/pricing', label: 'Pricing in GEL', hint: 'Pay only for the features you turn on' },
                  { href: '/whatsapp-helpdesk-georgia', label: 'WhatsApp helpdesk', hint: 'One inbox for every channel' },
                  { href: '/gel-invoicing-software', label: 'GEL invoicing', hint: 'BOG + TBC payment links built in' },
                  { href: '/sip-pbx-crm-georgia', label: 'SIP PBX + CRM', hint: 'Browser softphone with a Georgian DID' },
                  { href: '/docs', label: 'Documentation', hint: 'PBX, widget, API integration guides' },
                  { href: '/contact', label: 'Book a demo', hint: 'Tbilisi-based support, GEL pricing' },
                ],
              };
              // Prioritise links by post_type: comparisons want alternatives,
              // how-tos want docs, use_cases want pricing+features. Pick 4.
              const order: Record<string, string[]> = {
                comparison: ['/pricing', '/whatsapp-helpdesk-georgia', '/gel-invoicing-software', '/contact'],
                how_to: ['/docs', '/pricing', '/sip-pbx-crm-georgia', '/contact'],
                use_case: ['/pricing', '/whatsapp-helpdesk-georgia', '/gel-invoicing-software', '/sip-pbx-crm-georgia'],
                announcement: ['/pricing', '/contact', '/docs', '/whatsapp-helpdesk-georgia'],
                thought_leadership: ['/pricing', '/whatsapp-helpdesk-georgia', '/gel-invoicing-software', '/contact'],
              };
              const want = order[post.post_type] ?? ['/pricing', '/whatsapp-helpdesk-georgia', '/gel-invoicing-software', '/contact'];
              const items = all[lang];
              const picks = want
                .map((href) => items.find((i) => i.href === href))
                .filter(Boolean) as LinkItem[];
              return picks.map((it) => (
                <li key={it.href}>
                  <Link
                    href={it.href}
                    className="block rounded-lg border border-border bg-background hover:border-primary/40 hover:bg-primary/5 transition-colors px-4 py-3"
                  >
                    <div className="font-medium text-foreground">{it.label}</div>
                    <div className="text-xs text-muted-foreground mt-0.5">{it.hint}</div>
                  </Link>
                </li>
              ));
            })()}
          </ul>
        </aside>

        {post.faq_items?.length > 0 && (
          <BlogFaq
            items={post.faq_items}
            locale={lang}
            heading={lang === 'ka' ? 'ხშირად დასმული კითხვები' : 'Frequently asked questions'}
          />
        )}

        {/* CTA */}
        <div className="mt-12 rounded-2xl bg-primary/5 border border-primary/20 p-6 md:p-8">
          <h2 className="text-xl font-semibold mb-2">
            {lang === 'ka'
              ? 'სცადე EchoDesk უფასოდ 14 დღე'
              : 'Try EchoDesk free for 14 days'}
          </h2>
          <p className="text-muted-foreground mb-4">
            {lang === 'ka'
              ? 'ბარათი არ სჭირდება — ნახე თუ EchoDesk მუშაობს შენს გუნდში.'
              : 'No credit card required. See if EchoDesk fits your team.'}
          </p>
          <Link
            href="/registration"
            className="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground px-5 py-2.5 font-medium hover:bg-primary/90 transition-colors"
          >
            {lang === 'ka' ? 'დაიწყე უფასო ცდა' : 'Start free trial'}
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </article>

      {related.length > 0 && (
        <section className="container mx-auto max-w-6xl px-4 pb-16">
          <h2 className="text-xl font-semibold mb-6">
            {lang === 'ka' ? 'სხვა პოსტები' : 'Related posts'}
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {related.map((p) => (
              <BlogCard key={p.id} post={p} />
            ))}
          </div>
        </section>
      )}
    </>
  );
}
